GET http://localhost:5000/siswa?search=TKJ2022SISWA14

###

GET http://localhost:5000/siswa-profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFNpc3dhIjoiZTI3MzRmMTctYTIwOS00MGZiLThlMDktNmJiYzdhZWY4YzQyIiwibmlzblNpc3dhIjoiMTExMTExMTEyMiIsInRhaHVuQW5na2F0YW5TaXN3YSI6IjIwMjIiLCJuYW1hSnVydXNhblNpc3dhIjpudWxsLCJpYXQiOjE2Njk0MjU1NzIsImV4cCI6MTY3MDAzMDM3Mn0.aHitOOWr1d0mOW7Q9Ch73jRJRScJ9BZGTj7X5NNEEE0


###

POST http://localhost:5000/register-siswa
Content-Type: application/json

{
      "nama": "nur",
      "nisn": "nur",
      "password":"hamsah",
      "noHP": "081213221343",
      "jurusanId":"cc277e85-245b-4e98-8188-c91cfd88b805"
}
###
###

PATCH  http://localhost:5000/siswa-profile-update/d12fdc6f-d496-49de-bf6f-1a77b6d90a8d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFN0YWZmIjoiNzE3ZjU4MmQtOTAzZC00MDE0LWIzMzMtMTRjMTMxMDgyYmMxIiwibmFtYVN0YWZmIjoiUGFuaXRpYSBQUERCIiwidXNlcm5hbWVTdGFmZiI6InBwZGJAcHBkYi5jb20iLCJyb2xlU3RhZmYiOiJQUERCIiwiaWF0IjoxNjcwMTM0OTkyLCJleHAiOjE2NzA3Mzk3OTJ9.Vfj3iLo7_OegFCNBdsBF35QamQ-oEeT7QlfJC2kmo_c
Content-Type: application/json

{
      "status": "accepted"
}
###

POST http://localhost:5000/login-siswa
Content-Type: application/json

{
      "nisn": "nur",
      "password":"hamsah"
}


/////////////////////////////////////////////////////////////////////////////////





###
/// post jurusan siswa
POST http://localhost:5000/jurusan
Content-Type: application/json

{
    "nama":"ALL"
}

###
/// get jurusan siswa
GET http://localhost:5000/jurusan
###
/// delete jurusan siswa
DELETE  http://localhost:5000/jurusan/1e1fbd1b-a083-4669-8755-8ed02757f3c8
###
/// update jurusan siswa
PATCH   http://localhost:5000/jurusan/273b169d-6c8f-4538-8052-315f2cabb4bc
Content-Type: application/json

{
    "name":"tukang ngomel"
}

////////////////////////////////////////////////////////////////////////////////////////

###
/// post tagihan siswa
POST http://localhost:5000/tagihan
Content-Type: application/json

{
      "name": "gt",
      "description": "LAB praktek",
      "total": 450000,
      "kelas":"02",
      "angkatan":"2022",
      "periode":[
            {
                  "bulan":"Juli",
                  "total":10000,
                  "code":"JUL2022TKJ02"
            },
            {
                  "bulan":"Agustus",
                  "total":10000,
                  "code":"AUG2022TKJ02"
            },
            {
                  "bulan":"September",
                  "total":10000,
                  "code":"SEP2022TKJ02"
            }
      ],
      "jurusanId":"b726fd40-dd53-4f21-be1d-6e5cd19ce435"
    
}

###
/// get tagihan siswa
GET http://localhost:5000/tagihan-permanent
###
/// delete tagihan siswa
DELETE  http://localhost:5000/tagihan/8d2500b6-6420-4b5f-b4c4-6bcb002669ec
###
/// update tagihan siswa
PATCH   http://localhost:5000/tagihan/22a88ee5-ef42-4c7b-a307-d60a7cb19b28
Content-Type: application/json

{
    "name":"PembayarncSPP",
    "description":"bayra spp ketika hujan",
    "major_id":"47b54a65-e0c5-48bc-8d80-241a9fdcae15"
}

////////////////////////////////////////////////////////////////////////////////
/// STAFF
###

POST http://localhost:5000/staff-register
Content-Type: application/json

{
      "nama": "pak candara",
      "username": "canbdar@123",
      "password":"111",
      "noHP": "081213221343"
    
}
###

POST http://localhost:5000/staff-login
Content-Type: application/json

{
      "username": "s2s@mailinator.com",
      "password":"s2s@mailinator.com"
    
}
###

GET http://localhost:5000/staff
###

GET http://localhost:5000/staff-profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFN0YWZmIjoiYTNiYzVkMzgtZmVkNC00ODVmLWE0NWItYjc5YjlkNDI1Y2Y2IiwibmFtYVN0YWZmIjoicGFrIGNhbmRhcmEiLCJ1c2VybmFtZVN0YWZmIjoiY2FuYmRhckAxMjMiLCJpYXQiOjE2Njk0MzEyMTQsImV4cCI6MTY3MDAzNjAxNH0.RTD8PxJM9nsG-uEE6c1pVw5saFfxEkkfJqoT0Sz0F2s

